name: Compile

on:
  pull_request:
    paths:
      - ".github/workflows/compile-fw.yml"
      - "esp-sensor-node.ino"

  push:
    paths:
      - ".github/workflows/compile-fw.yml"
      - "esp-sensor-node.ino"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false

      matrix:
        board:
          - fqbn: esp8266:esp8266:generic
            platforms: |
              - name: esp8266:esp8266
                source-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: arduino/compile-sketches@main
        with:
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          enable-deltas-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          libraries: |
            - source-path: ./
            - source-url: https://github.com/PaulStoffregen/OneWire.git
            - source-url: https://github.com/milesburton/Arduino-Temperature-Control-Library.git
            - source-url: https://github.com/adafruit/Adafruit_BusIO.git
            - source-url: https://github.com/adafruit/Adafruit_Sensor.git
            - source-url: https://github.com/adafruit/Adafruit_BME680.git
            - source-url: https://github.com/adafruit/Adafruit_HTS221.git
            - source-url: https://github.com/adafruit/Adafruit_LPS2X.git
            - source-url: https://github.com/107-systems/107-Arduino-TSL2550.git

          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          sketch-paths: ./

      - name: Save memory usage change report as artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
